export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
    'hello': 'Hola',
    'seeMore': 'Ver Más',
    'search': 'Buscar',
    'searchMovie': 'Buscar Película',
    'movies': 'Películas',
    'home': 'Inicio',
    'synopsis': 'Sinopsis',
    'famousPhrase': 'Frace Celebre',
    'popularity': 'Popularidad',
    'averageVote': 'Voto Promedio',
    'return': 'Regresar',
    'logIn': 'Iniciar Sesión',
    'logOut': 'Cerrar Sesión',
    'language': 'Idioma',
    'english': 'Ingles',
    'spanish': 'Español',
    'upcomingMovies': 'Películas en Cartelera',
    'popularMovies': 'Películas Populares',
    'childrenMovies': 'Películas para Niños',
    'pleaseLogin': 'Por favor Ingrese',
    'loginWith': 'Ingresar Con',
    'welcome': 'Bienvenido a MovieCorner, aqui podras buscar toda la información de tus peliculas favoritas.',
    'redirect': 'Click aqui, para ir a la pagina principal',
    'go': 'Ir!',
    'notFound': 'Pagina no Encontrada',
    'watchTrailer': 'Ver Trailer',
    'celebratePhrase': 'Frase Celebre'
};
